name: tests
on:
  push:
    branches-ignore: [main]
  workflow_dispatch:

jobs:
  xNuts-pdr3:
    uses: salesforcecli/github-workflows/.github/workflows/externalNut.yml@main
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        command:
          - 'yarn test:nuts:tracking'
    with:
      packageName: '@salesforce/source-tracking'
      externalProjectGitUrl: 'https://github.com/salesforcecli/plugin-deploy-retrieve'
      command: ${{matrix.command}}
      os: ${{matrix.os}}
      useCache: false
    secrets:
      TESTKIT_AUTH_URL: ${{ secrets.TESTKIT_AUTH_URL }}
